Logistic Regression

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [3]:
## create the dataset
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=46)

In [4]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,1.243829,1.043283,-0.780266,-0.099654,-0.635318,0.141214,0.803631,-0.943278,-0.650539,1.689416
1,-0.573410,-0.333020,0.063746,0.649135,0.101909,0.513285,-0.241628,0.927425,0.364067,0.214251
2,-1.228897,-0.077742,0.514770,0.620475,-0.537131,-1.089095,-0.682475,0.657074,-1.014586,-0.741600
3,-0.020225,-0.843452,0.484792,-0.960576,0.169012,-0.543333,-0.218603,-0.028094,2.598768,-0.302727
4,1.810558,1.167362,-1.069528,-0.280091,-0.364957,-1.409534,1.140948,0.181567,-1.042291,-0.102279
...,...,...,...,...,...,...,...,...,...,...
995,1.860200,-0.878094,-0.817200,-0.861805,0.072948,-1.923610,1.049611,-0.431558,0.208530,-0.322896
996,-0.555674,-0.831097,-0.207547,1.177962,0.642363,0.270921,-0.116903,0.168740,0.035474,-0.293846
997,1.015767,-1.763042,-1.364511,1.400949,-0.000010,0.113101,0.972924,-0.069564,0.250993,-0.119750
998,-0.606424,-1.370084,0.862463,-0.933875,-1.086946,1.298465,-0.601671,-1.412996,1.546192,1.617880


In [5]:
pd.DataFrame(y)

,0
0,0
1,1
2,1
3,0
4,1
...,...
995,0
996,1
997,1
998,0


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=46)

In [7]:
## Model training
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [8]:
logistic.fit(X_train,y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [9]:
y_pred=logistic.predict(X_test)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1])

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [11]:
score=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print(score)
print(cm)
print(cr)

0.97
[[162   3]
 [  6 129]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       165
           1       0.98      0.96      0.97       135

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



**Hyperparameter Tuning** and **Cross Validation**

In [12]:
model = LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg','sag', 'saga']

In [13]:
params=dict(penalty=penalty,C=c_values,solver=solver)

In [14]:
## Grid search cv
from sklearn.model_selection import GridSearchCV,StratifiedKFold
cv=StratifiedKFold()
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [15]:
grid

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l2'


In [16]:
grid.fit(X_train,y_train)

d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.d

,estimator,LogisticRegression()
,param_grid,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,error_score,nan
,return_train_score,False
,penalty,'l1'


In [17]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'liblinear'}

In [18]:
grid.best_score_

np.float64(0.9642857142857142)

In [19]:
y_pred_grid=grid.predict(X_test)

In [20]:
score=accuracy_score(y_test,y_pred_grid)
cm=confusion_matrix(y_test,y_pred_grid)
cr=classification_report(y_test,y_pred_grid)
print(score)
print(cm)
print(cr)

0.9733333333333334
[[162   3]
 [  5 130]]
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       165
           1       0.98      0.96      0.97       135

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



**Randomized SearchCV**

In [21]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg','sag', 'saga']
params=dict(penalty=penalty,C=c_values,solver=solver)

In [22]:
randomCV=RandomizedSearchCV(estimator=model,param_distributions=params,cv=cv,n_jobs=-1,scoring='accuracy')

In [23]:
randomCV.fit(X_train,y_train)

d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual

,estimator,LogisticRegression()
,param_distributions,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [24]:
randomCV.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 1.0}

In [25]:
randomCV.best_score_

np.float64(0.9628571428571429)

In [26]:
y_pred_rcv=randomCV.predict(X_test)
score=accuracy_score(y_test,y_pred_rcv)
cm=confusion_matrix(y_test,y_pred_rcv)
cr=classification_report(y_test,y_pred_rcv)
print(score)
print(cm)
print(cr)


0.97
[[162   3]
 [  6 129]]
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       165
           1       0.98      0.96      0.97       135

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



#### **Logistic Regression for Multiclass Classification Problem**

In [27]:
X,y=make_classification(n_samples=1000,n_features=10,n_informative=4,n_classes=4,random_state=50)

In [28]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9
0,0.668074,-0.908162,1.884199,2.242292,0.515877,-1.987496,-1.482731,0.838326,-0.052434,0.586648
1,-1.497587,-3.329128,0.546956,1.743453,-0.850567,-2.402241,1.525900,0.604504,-0.983610,-1.107958
2,0.840054,0.597405,-0.852157,-0.949310,-0.363844,1.293994,-0.424741,0.251930,-2.531485,-0.041974
3,0.271078,-1.199962,1.906641,1.940662,0.825916,-1.662044,0.387913,-0.762271,-0.067804,-2.952724
4,1.179011,1.852383,0.569146,-0.234706,0.026617,0.523076,-0.279272,-0.699205,0.444845,0.503809
...,...,...,...,...,...,...,...,...,...,...
995,1.733354,1.777596,0.469765,-0.581640,-0.358276,1.012241,-0.864823,-1.730321,0.173663,-2.022606
996,0.610445,-1.062977,-0.753612,-0.039629,-1.752841,-0.657488,-2.074203,1.109493,2.163530,2.337058
997,1.075167,0.956796,-0.355261,-0.576362,-1.991537,0.996746,0.935774,0.337723,0.357781,0.600715
998,-0.378868,1.628521,0.642408,-0.317804,1.491377,0.468271,-0.299905,-1.606532,0.869144,-1.142438


In [29]:
pd.DataFrame(y)

,0
0,2
1,2
2,1
3,3
4,1
...,...
995,3
996,1
997,0
998,3


In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=50)

In [31]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(multi_class='ovr')
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)
y_pred

d:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1281: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array([1, 2, 0, 0, 2, 0, 3, 0, 0, 0, 2, 0, 1, 3, 0, 3, 3, 0, 3, 1, 3, 1,
       2, 3, 2, 2, 0, 0, 3, 3, 0, 0, 0, 2, 1, 2, 3, 0, 1, 3, 2, 0, 1, 3,
       2, 3, 0, 3, 0, 2, 2, 2, 1, 1, 1, 0, 3, 1, 2, 0, 1, 2, 2, 0, 2, 1,
       0, 0, 0, 0, 2, 0, 0, 1, 2, 3, 0, 3, 1, 0, 0, 3, 0, 3, 3, 1, 2, 1,
       1, 3, 1, 0, 3, 3, 3, 1, 0, 1, 1, 3, 3, 3, 1, 0, 2, 0, 0, 1, 3, 1,
       1, 0, 2, 0, 2, 0, 1, 0, 1, 2, 2, 3, 3, 3, 0, 0, 0, 3, 2, 2, 0, 3,
       0, 1, 2, 0, 3, 0, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 3, 3, 0, 3,
       0, 1, 0, 0, 1, 2, 2, 3, 1, 3, 3, 2, 2, 3, 0, 1, 3, 1, 1, 2, 3, 3,
       0, 2, 1, 3, 3, 2, 1, 0, 3, 2, 3, 2, 2, 2, 0, 3, 1, 1, 3, 0, 1, 0,
       3, 0, 2, 1, 3, 3, 2, 1, 0, 0, 2, 3, 1, 3, 0, 2, 2, 2, 0, 0, 0, 0,
       0, 3, 2, 1, 1, 0, 3, 0, 0, 3, 3, 2, 3, 2, 3, 1, 2, 2, 2, 3, 2, 3,
       3, 2, 0, 2, 3, 1, 0, 1, 3, 2, 0, 0, 1, 2, 0, 3, 2, 0, 1, 2, 3, 2,
       3, 0, 0, 3, 2, 3, 1, 0, 2, 3, 2, 1, 2, 2, 3, 1, 2, 0, 0, 3, 3, 1,
       0, 1, 0, 1, 2, 3, 1, 0, 3, 0, 1, 1, 0, 2])

In [32]:
score=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print(score)
print(cm)
print(cr)

0.6633333333333333
[[57  9  0 16]
 [10 47  3 11]
 [ 1 10 55 10]
 [17  0 14 40]]
              precision    recall  f1-score   support

           0       0.67      0.70      0.68        82
           1       0.71      0.66      0.69        71
           2       0.76      0.72      0.74        76
           3       0.52      0.56      0.54        71

    accuracy                           0.66       300
   macro avg       0.67      0.66      0.66       300
weighted avg       0.67      0.66      0.67       300



In [33]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['lbfgs', 'liblinear', 'newton-cg','sag', 'saga']
params=dict(penalty=penalty,C=c_values,solver=solver)
randomCV=RandomizedSearchCV(estimator=model,param_distributions=params,cv=cv,n_jobs=-1,scoring='accuracy')

In [34]:
randomCV.fit(X_train,y_train)

d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
20 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "d:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "d:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1218, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual

,estimator,LogisticRegression()
,param_distributions,"{'C': [100, 10, ...], 'penalty': ['l1', 'l2', ...], 'solver': ['lbfgs', 'liblinear', ...]}"
,n_iter,10
,scoring,'accuracy'
,n_jobs,-1
,refit,True
,cv,StratifiedKFo...shuffle=False)
,verbose,0
,pre_dispatch,'2*n_jobs'
,random_state,None
,error_score,nan


In [35]:
randomCV.best_score_

np.float64(0.7385714285714287)

In [36]:
y_pred=randomCV.predict(X_test)
score=accuracy_score(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
cr=classification_report(y_test,y_pred)
print(score)
print(cm)
print(cr)

0.68
[[56 11  0 15]
 [ 6 50  1 14]
 [ 1  9 52 14]
 [13  0 12 46]]
              precision    recall  f1-score   support

           0       0.74      0.68      0.71        82
           1       0.71      0.70      0.71        71
           2       0.80      0.68      0.74        76
           3       0.52      0.65      0.57        71

    accuracy                           0.68       300
   macro avg       0.69      0.68      0.68       300
weighted avg       0.70      0.68      0.68       300

